//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM01_4IPIP321_Trushkin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int ID { get; set; }
        public Nullable<double> NotPayed { get; set; }
        public Nullable<double> Payed { get; set; }
        public Nullable<System.DateTime> Period { get; set; }
        public Nullable<int> CitizenID { get; set; }
    
        public virtual Citizens Citizens { get; set; }
    }
}
