//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM01_4IPIP321_Trushkin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> CitizenID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> EmployerID { get; set; }
    
        public virtual Citizens Citizens { get; set; }
        public virtual Employers Employers { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
